# Generated by Django 4.2.7 on 2025-03-16 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("target_criteria", models.JSONField(blank=True, default=dict)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("total_targets", models.IntegerField(default=0)),
                ("total_sent", models.IntegerField(default=0)),
                ("total_responses", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Campaign",
                "verbose_name_plural": "Campaigns",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="CampaignTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("responded", "Responded"),
                            ("failed", "Failed"),
                            ("excluded", "Excluded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("scheduled_time", models.DateTimeField(blank=True, null=True)),
                ("sent_time", models.DateTimeField(blank=True, null=True)),
                ("response_time", models.DateTimeField(blank=True, null=True)),
                ("message_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "delivery_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Campaign Target",
                "verbose_name_plural": "Campaign Targets",
            },
        ),
        migrations.CreateModel(
            name="ConversationState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("possible_transitions", models.JSONField(blank=True, default=list)),
                ("prompts", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Conversation State",
                "verbose_name_plural": "Conversation States",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "preferred_language",
                    models.CharField(default="english", max_length=50),
                ),
                ("property_details", models.JSONField(blank=True, default=dict)),
                ("loan_requirements", models.JSONField(blank=True, default=dict)),
                (
                    "conversation_state",
                    models.CharField(default="initial", max_length=50),
                ),
                ("interest_level", models.FloatField(default=0.0)),
                (
                    "last_contacted",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("next_contact_date", models.DateTimeField(blank=True, null=True)),
                ("do_not_contact", models.BooleanField(default=False)),
                ("consents", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
            },
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("language_code", models.CharField(default="en", max_length=10)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("marketing", "Marketing"),
                            ("utility", "Utility"),
                            ("authentication", "Authentication"),
                        ],
                        max_length=50,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "header_text",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "footer_text",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("sample_values", models.JSONField(blank=True, default=dict)),
                ("is_approved", models.BooleanField(default=False)),
                ("approval_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Template",
                "verbose_name_plural": "Templates",
                "unique_together": {("name", "language_code")},
            },
        ),
        migrations.CreateModel(
            name="Interaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        max_length=10,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("audio", "Audio"),
                            ("template", "Template"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("media_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "whatsapp_message_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "detected_intent",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "conversation_state",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("language", models.CharField(default="english", max_length=50)),
                ("ai_confidence", models.FloatField(default=1.0)),
                ("ai_analysis", models.JSONField(blank=True, default=dict)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="agent.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interaction",
                "verbose_name_plural": "Interactions",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="FollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "follow_up_type",
                    models.CharField(
                        choices=[
                            ("general", "General Follow-up"),
                            ("interest_rate_drop", "Interest Rate Drop"),
                            ("property_value_increase", "Property Value Increase"),
                            ("new_product_launch", "New Product Launch"),
                            ("seasonal_promotion", "Seasonal Promotion"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
                (
                    "message_template",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("custom_message", models.TextField(blank=True, null=True)),
                (
                    "follow_up_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("result_notes", models.TextField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followups",
                        to="agent.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Follow-up",
                "verbose_name_plural": "Follow-ups",
                "ordering": ["-scheduled_date"],
            },
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["next_contact_date"], name="agent_custo_next_co_1dad9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["conversation_state"], name="agent_custo_convers_ff87d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["interest_level"], name="agent_custo_interes_0e5fe7_idx"
            ),
        ),
        migrations.AddField(
            model_name="campaigntarget",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="targets",
                to="agent.campaign",
            ),
        ),
        migrations.AddField(
            model_name="campaigntarget",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaign_targets",
                to="agent.customer",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaigns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="campaigns",
                to="agent.template",
            ),
        ),
        migrations.AddIndex(
            model_name="interaction",
            index=models.Index(
                fields=["-timestamp"], name="agent_inter_timesta_80e2f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interaction",
            index=models.Index(
                fields=["customer", "-timestamp"], name="agent_inter_custome_3ed411_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interaction",
            index=models.Index(
                fields=["detected_intent"], name="agent_inter_detecte_5e012b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="followup",
            index=models.Index(
                fields=["scheduled_date", "status"],
                name="agent_follo_schedul_4b222f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="followup",
            index=models.Index(
                fields=["customer", "status"], name="agent_follo_custome_83d914_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="campaigntarget",
            unique_together={("campaign", "customer")},
        ),
    ]
